# API KEYS AND PASSPHRASE DETAILS HERE
BB_KEY = "<YOUR BYBIT (OR OTHER EXCHANGE) ACCOUNT API KEY HERE>"
BB_SECRET = "<YOUR BYBIT (OR OTHER EXCHANGE) ACCOUNT SECRET KEY HERE>"

BB_KEY2 = "<YOUR SECOND BYBIT (OR OTHER EXCHANGE) ACCOUNT API KEY HERE>"
BB_SECRET2 = "<YOUR SECOND BYBIT (OR OTHER EXCHANGE) ACCOUNT SECRET KEY HERE>"

BNC_KEY = '<YOUR BINANCE (OR OTHER EXCHANGE) API KEY HERE>'
BNC_SECRET = '<YOUR BINANCE (OR OTHER EXCHANGE) SECRET KEY HERE>'

WEBHOOK_PASSPHRASE = '<YOUR PASSPHRASE HERE>'

IP = '<YOUR IP HERE>'

